/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ckcDC3H1CpP
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Bricolage_Grotesque } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

bricolage_grotesque({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function AccessDeniedComponent() {
  return (
    <div className="flex h-screen w-full flex-col items-center justify-center bg-gray-950 px-4 py-12 dark:bg-gray-950">
      <div className="relative mx-auto max-w-md overflow-hidden rounded-lg bg-gray-900 shadow-lg dark:bg-gray-800">
        <div className="absolute inset-0 bg-[url('/imperial-insignia.svg')] bg-no-repeat bg-contain opacity-10" />
        <div className="relative z-10 space-y-6 p-8 text-center">
          <div className="space-y-2">
            <h1 className="text-4xl font-bold tracking-tight text-red-500">ACCESS DENIED</h1>
            <p className="text-gray-400">
              Unauthorized access to Imperial facilities is strictly prohibited. Violators will be subject to immediate
              termination.
            </p>
          </div>
          <div className="relative h-40 w-full">
            <img alt="Death Star" className="object-contain" fill src="/placeholder.svg" />
          </div>
        </div>
      </div>
    </div>
  )
}
