/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/fcaxAThe0cL
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function CommandCenter() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 bg-black text-[#ffd700] font-semibold">
      <div className="container grid gap-8 px-4 md:px-6">
        <div className="space-y-4">
          <h1 className="text-4xl font-bold tracking-tight">Welcome to the Empire Command Center</h1>
          <p className="text-gray-400 max-w-[700px]">
            Explore the key areas and access points on the Empire's ultimate weapon, the Death Star.
          </p>
        </div>
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          <div className="rounded-lg border border-gray-800 p-6 shadow-sm">
            <h3 className="text-2xl font-semibold">Hangar Bay</h3>
            <p className="text-sm text-gray-400 mt-2">
              The massive hangar bay houses the Death Star's fleet of TIE fighters and shuttles. Access requires
              Imperial Pilot clearance.
            </p>
            <div className="mt-4 flex items-center gap-2">
              <KeyIcon className="w-4 h-4 text-gray-400" />
              <span className="text-sm text-gray-400">Imperial Pilot</span>
            </div>
          </div>
          <div className="rounded-lg border border-gray-800 p-6 shadow-sm">
            <h3 className="text-2xl font-semibold">Command Center</h3>
            <p className="text-sm text-gray-400 mt-2">
              The nerve center of the Death Star, where the Empire's top officers coordinate operations. Access requires
              Imperial Officer clearance.
            </p>
            <div className="mt-4 flex items-center gap-2">
              <KeyIcon className="w-4 h-4 text-gray-400" />
              <span className="text-sm text-gray-400">Imperial Officer</span>
            </div>
          </div>
          <div className="rounded-lg border border-gray-800 p-6 shadow-sm">
            <h3 className="text-2xl font-semibold">Detention Block</h3>
            <p className="text-sm text-gray-400 mt-2">
              The high-security detention block holds the Empire's most valuable prisoners. Access requires Imperial
              Security clearance.
            </p>
            <div className="mt-4 flex items-center gap-2">
              <KeyIcon className="w-4 h-4 text-gray-400" />
              <span className="text-sm text-gray-400">Imperial Security</span>
            </div>
          </div>
          <div className="rounded-lg border border-gray-800 p-6 shadow-sm">
            <h3 className="text-2xl font-semibold">Reactor Core</h3>
            <p className="text-sm text-gray-400 mt-2">
              The powerful reactor core powers the Death Star's superlaser. Access requires Imperial Engineer clearance.
            </p>
            <div className="mt-4 flex items-center gap-2">
              <KeyIcon className="w-4 h-4 text-gray-400" />
              <span className="text-sm text-gray-400">Imperial Engineer</span>
            </div>
          </div>
          <div className="rounded-lg border border-gray-800 p-6 shadow-sm">
            <h3 className="text-2xl font-semibold">Trash Compactor</h3>
            <p className="text-sm text-gray-400 mt-2">
              The trash compactor is a hazardous area used to dispose of waste. Access requires Imperial Sanitation
              clearance.
            </p>
            <div className="mt-4 flex items-center gap-2">
              <KeyIcon className="w-4 h-4 text-gray-400" />
              <span className="text-sm text-gray-400">Imperial Sanitation</span>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

function KeyIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="7.5" cy="15.5" r="5.5" />
      <path d="m21 2-9.6 9.6" />
      <path d="m15.5 7.5 3 3L22 7l-3-3" />
    </svg>
  )
}
