/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/eVaQP8dI217
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Bricolage_Grotesque } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

bricolage_grotesque({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/


export function Deathstar() {
  return (
    <div className="flex flex-col w-full min-h-screen text-[#f1f1f1]">
      <main className="flex-1 px-5">
        <div className="mt-6">
          <img
            alt="Map"
            className="w-full h-auto rounded-lg"
            height={800}
            src="deathstar-map.jpg"
         
            width={1200}
          />
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-6">
          <div className="rounded-lg border shadow p-4">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-bold text-[#ffd700]">TIE Fighters</h2>
                <p className="text-4xl font-bold text-[#f1f1f1]">12,345</p>
              </div>
              <SpaceIcon className="w-12 h-12 text-[#9b9b9b]" />
            </div>
          </div>
          <div className="rounded-lg border shadow p-4">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-bold text-[#ffd700]">Stormtroopers</h2>
                <p className="text-4xl font-bold text-[#f1f1f1]">54,321</p>
              </div>
              <ShieldIcon className="w-12 h-12 text-[#9b9b9b]" />
            </div>
          </div>
          <div className="rounded-lg border shadow p-4">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-bold text-[#ffd700]">Energy Remaining</h2>
                <p className="text-4xl font-bold text-[#f1f1f1]">78%</p>
              </div>
              <BatteryIcon className="w-12 h-12 text-[#9b9b9b]" />
            </div>
          </div>
          <div className="rounded-lg border shadow p-4">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-bold text-[#ffd700]">Main Weapon Status</h2>
                <p className="text-4xl font-bold text-[#f1f1f1]">Online</p>
              </div>
              <LaptopIcon className="w-12 h-12 text-[#9b9b9b]" />
            </div>
          </div>
          <div className="rounded-lg border shadow p-4">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-bold text-[#ffd700]">Rebel Scum Captured</h2>
                <p className="text-4xl font-bold text-[#f1f1f1]">2,345</p>
              </div>
              <HandIcon className="w-12 h-12 text-[#9b9b9b]" />
            </div>
          </div>
          <div className="rounded-lg border shadow p-4">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-bold text-[#ffd700]">Proton Torpedoes</h2>
                <p className="text-4xl font-bold text-[#f1f1f1]">987</p>
              </div>
              <RocketIcon className="w-12 h-12 text-[#9b9b9b]" />
            </div>
          </div>
          <div className="rounded-lg border shadow p-4">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-bold text-[#ffd700]">Deflector Shield</h2>
                <p className="text-4xl font-bold text-[#f1f1f1]">99.9%</p>
              </div>
              <ShieldIcon className="w-12 h-12 text-[#9b9b9b]" />
            </div>
          </div>
          <div className="rounded-lg border shadow p-4">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-bold text-[#ffd700]">Tractor Beam</h2>
                <p className="text-4xl font-bold text-[#f1f1f1]">Operational</p>
              </div>
              <TractorIcon className="w-12 h-12 text-[#9b9b9b]" />
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

function BatteryIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="16" height="10" x="2" y="7" rx="2" ry="2" />
      <line x1="22" x2="22" y1="11" y2="13" />
    </svg>
  )
}


function HandIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 11V6a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v0" />
      <path d="M14 10V4a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v2" />
      <path d="M10 10.5V6a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v8" />
      <path d="M18 8a2 2 0 1 1 4 0v6a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15" />
    </svg>
  )
}


function LaptopIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 16V7a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v9m16 0H4m16 0 1.28 2.55a1 1 0 0 1-.9 1.45H3.62a1 1 0 0 1-.9-1.45L4 16" />
    </svg>
  )
}


function RocketIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z" />
      <path d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z" />
      <path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0" />
      <path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />
    </svg>
  )
}


function ShieldIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" />
    </svg>
  )
}


function SpaceIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 17v1c0 .5-.5 1-1 1H3c-.5 0-1-.5-1-1v-1" />
    </svg>
  )
}


function TractorIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m10 11 11 .9c.6 0 .9.5.8 1.1l-.8 5h-1" />
      <path d="M16 18h-5" />
      <path d="M18 5a1 1 0 0 0-1 1v5.573" />
      <path d="M3 4h9l1 7.246" />
      <path d="M4 11V4" />
      <path d="M7 15h.01" />
      <path d="M8 10.1V4" />
      <circle cx="18" cy="18" r="2" />
      <circle cx="7" cy="15" r="5" />
    </svg>
  )
}
