/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5F1TQBT5PJH
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"

export function Hangar() {
  return (
    <main className="flex flex-col h-screen w-full bg-[#1e1e1e] text-white">
      <div>
        <div className="relative">
          <img alt="Banner" className="object-cover" fill src="hangar.gif" />
        </div>
      </div>
      <div className="flex-1 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 p-8">
        <Card>
          <CardHeader>
            <CardTitle>Active Pilots</CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-2">
              <li className="flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  <Avatar>
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div>
                    <div className="font-medium">Jyn Darklighter</div>
                    <div className="text-[#b3b3b3] text-sm">Ready</div>
                  </div>
                </div>
              </li>
              <li className="flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  <Avatar>
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>LO</AvatarFallback>
                  </Avatar>
                  <div>
                    <div className="font-medium">Leia Organa</div>
                    <div className="text-[#b3b3b3] text-sm">On Mission</div>
                  </div>
                </div>
              </li>
              <li className="flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  <Avatar>
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>HS</AvatarFallback>
                  </Avatar>
                  <div>
                    <div className="font-medium">Han Solo</div>
                    <div className="text-[#b3b3b3] text-sm">Resting</div>
                  </div>
                </div>
                <Button size="icon" variant="ghost">
                  <ChevronRightIcon className="h-5 w-5" />
                </Button>
              </li>
            </ul>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Hangar Status</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-3 gap-4 text-center">
              <div>
                <div className="text-4xl font-bold">24</div>
                <div className="text-[#b3b3b3] text-sm">Available</div>
              </div>
              <div>
                <div className="text-4xl font-bold">3</div>
                <div className="text-[#b3b3b3] text-sm">Damaged</div>
              </div>
              <div>
                <div className="text-4xl font-bold">12</div>
                <div className="text-[#b3b3b3] text-sm">Deployed</div>
              </div>
            </div>
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 mt-8">
              <div className="bg-[#121212] rounded-lg p-4 flex flex-col items-center justify-center">
                <PlaneIcon className="h-8 w-8" />
                <div className="font-medium mt-2">X-Wing</div>
                <div className="text-[#b3b3b3] text-sm">Available</div>
              </div>
              <div className="bg-[#121212] rounded-lg p-4 flex flex-col items-center justify-center">
                <PlaneIcon className="h-8 w-8" />
                <div className="font-medium mt-2">TIE Fighter</div>
                <div className="text-[#b3b3b3] text-sm">Deployed</div>
              </div>
              <div className="bg-[#121212] rounded-lg p-4 flex flex-col items-center justify-center">
                <PlaneIcon className="h-8 w-8" />
                <div className="font-medium mt-2">Y-Wing</div>
                <div className="text-[#b3b3b3] text-sm">Damaged</div>
              </div>
              <div className="bg-[#121212] rounded-lg p-4 flex flex-col items-center justify-center">
                <PlaneIcon className="h-8 w-8" />
                <div className="font-medium mt-2">TIE Interceptor</div>
                <div className="text-[#b3b3b3] text-sm">Available</div>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Dock Ports</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div>
                <div className="text-[#b3b3b3] text-sm">Dock Port 1</div>
                <div className="text-lg font-medium">X-Wing</div>
                <div className="text-[#b3b3b3] text-sm">Available</div>
              </div>
              <div>
                <div className="text-[#b3b3b3] text-sm">Dock Port 2</div>
                <div className="text-lg font-medium">TIE Fighter</div>
                <div className="text-[#b3b3b3] text-sm">Deployed</div>
              </div>
              <div>
                <div className="text-[#b3b3b3] text-sm">Dock Port 3</div>
                <div className="text-lg font-medium">Y-Wing</div>
                <div className="text-[#b3b3b3] text-sm">Damaged</div>
              </div>
              <div>
                <div className="text-[#b3b3b3] text-sm">Dock Port 4</div>
                <div className="text-lg font-medium">TIE Interceptor</div>
                <div className="text-[#b3b3b3] text-sm">Available</div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </main>
  )
}

function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}


function PlaneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.8 19.2 16 11l3.5-3.5C21 6 21.5 4 21 3c-1-.5-3 0-4.5 1.5L13 8 4.8 6.2c-.5-.1-.9.1-1.1.5l-.3.5c-.2.5-.1 1 .3 1.3L9 12l-2 3H4l-1 1 3 2 2 3 1-1v-3l3-2 3.5 5.3c.3.4.8.5 1.3.3l.5-.2c.4-.3.6-.7.5-1.2z" />
    </svg>
  )
}
