name: CI

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

  merge_group:

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

env:
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  prefetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 22.20.0
          cache: npm

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

  build:
    needs: [prefetch]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 22.20.0
          cache: npm

      - name: Update npm
        run: npm install -g npm@latest

      - name: Next.js cache
        uses: actions/cache@v4.3.0
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

  test-unit:
    needs: [prefetch]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 22.20.0
          cache: npm

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Unit tests
        run: npm test

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: docker/setup-qemu-action@v3.6.0
      - uses: docker/setup-buildx-action@v3.11.1
      - run: cp .env.local.example .env.local
      - name: Build Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          file: ./Dockerfile
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
